version: '3'
services:  
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    image: api
    ports:
     - "5001:5001"

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    image: client
    depends_on:
      - api
    ports:
      - "3000:80"

